import 'preset_weapon_traits.dart';
import 'weapon.dart';
import 'weapon_availability.dart';
import 'weapon_group.dart';
import 'weapon_specialisation.dart';

const boltWeapons = WeaponGroup(
  name: 'Bolt Weapons',
  weapons: [
    Weapon(
      id: 1,
      name: 'Bolt Pistol',
      specialisation: WeaponSpecialisation.pistol,
      damage: '8',
      range: 'Medium',
      mag: 2,
      enc: 1,
      cost: 4000,
      availability: WeaponAvailability.scarce,
      source: 'core book',
      traits: [
        weaponTraitBurst,
        weaponTraitClose,
        weaponTraitLoud,
        weaponTraitPenetrating4,
        weaponTraitSpread,
      ],
    ),
    Weapon(
      id: 2,
      name: 'Boltgun',
      specialisation: WeaponSpecialisation.longGun,
      damage: '8',
      range: 'Long',
      mag: 4,
      enc: 2,
      cost: 5000,
      availability: WeaponAvailability.scarce,
      source: 'core book',
      traits: [
        weaponTraitLoud,
        weaponTraitPenetrating4,
        weaponTraitRapidFire2,
        weaponTraitSpread,
        weaponTraitTwoHanded,
      ],
    ),
    Weapon(
      id: 3,
      name: 'Heavy Bolter',
      specialisation: WeaponSpecialisation.ordnance,
      damage: '10',
      range: 'Long',
      mag: 6,
      enc: 3,
      cost: 9000,
      availability: WeaponAvailability.rare,
      source: 'core book',
      traits: [
        weaponTraitHeavy4,
        weaponTraitPenetrating5,
        weaponTraitLoud,
        weaponTraitRapidFire3,
        weaponTraitSpread,
        weaponTraitTwoHanded,
      ],
    ),
  ],
);

const flameWeapons = WeaponGroup(
  name: 'Flame Weapons',
  weapons: [
    Weapon(
      id: 4,
      name: 'Hand Flamer',
      specialisation: WeaponSpecialisation.pistol,
      damage: '7',
      range: 'Short',
      mag: 2,
      enc: 1,
      cost: 500,
      availability: WeaponAvailability.rare,
      source: 'core book',
      traits: [
        weaponTraitClose,
        weaponTraitFlamer,
        weaponTraitInflictAblaze,
        weaponTraitLoud,
      ],
    ),
    Weapon(
      id: 5,
      name: 'Flamer',
      specialisation: WeaponSpecialisation.longGun,
      damage: '8',
      range: 'Medium',
      mag: 4,
      enc: 2,
      cost: 1000,
      availability: WeaponAvailability.scarce,
      source: 'core book',
      traits: [
        weaponTraitFlamer,
        weaponTraitInflictAblaze,
        weaponTraitLoud,
        weaponTraitTwoHanded,
      ],
    ),
  ],
);

const lasWeapons = WeaponGroup(
  name: 'Las Weapons',
  weapons: [
    Weapon(
      id: 6,
      name: 'Laspistol',
      specialisation: WeaponSpecialisation.pistol,
      damage: '5',
      range: 'Medium',
      mag: 2,
      enc: 0,
      cost: 400,
      availability: WeaponAvailability.common,
      source: 'core book',
      traits: [
        weaponTraitBurst,
        weaponTraitClose,
        weaponTraitLoud,
        weaponTraitReliable,
      ],
    ),
    Weapon(
      id: 7,
      name: 'Lasgun',
      specialisation: WeaponSpecialisation.longGun,
      damage: '6',
      range: 'Long',
      mag: 4,
      enc: 2,
      cost: 600,
      availability: WeaponAvailability.common,
      source: 'core book',
      traits: [
        weaponTraitBurst,
        weaponTraitLoud,
        weaponTraitReliable,
        weaponTraitTwoHanded,
      ],
    ),
    Weapon(
      id: 8,
      name: 'Las Carbine',
      specialisation: WeaponSpecialisation.longGun,
      damage: '5',
      range: 'Medium',
      mag: 3,
      enc: 1,
      cost: 800,
      availability: WeaponAvailability.common,
      source: 'core book',
      traits: [
        weaponTraitBurst,
        weaponTraitLoud,
        weaponTraitReliable,
        weaponTraitTwoHanded,
      ],
    ),
    Weapon(
      id: 9,
      name: 'Long Las',
      specialisation: WeaponSpecialisation.longGun,
      damage: '6',
      range: 'Extreme',
      mag: 2,
      enc: 2,
      cost: 1000,
      availability: WeaponAvailability.scarce,
      source: 'core book',
      traits: [
        weaponTraitBurst,
        weaponTraitPenetrating1,
        weaponTraitReliable,
        weaponTraitTwoHanded,
      ],
    ),
    Weapon(
      id: 10,
      name: 'Hot-Shot Laspistol',
      specialisation: WeaponSpecialisation.pistol,
      damage: '8',
      range: 'Medium',
      mag: 2,
      enc: 2,
      cost: 900,
      availability: WeaponAvailability.rare,
      source: 'core book',
      traits: [
        weaponTraitBurst,
        weaponTraitLoud,
        weaponTraitPenetrating2,
      ],
    ),
    Weapon(
      id: 11,
      name: 'Hot-Shot Lasgun',
      specialisation: WeaponSpecialisation.longGun,
      damage: '8',
      range: 'Long',
      mag: 3,
      enc: 3,
      cost: 1000,
      availability: WeaponAvailability.rare,
      source: 'core book',
      traits: [
        weaponTraitBurst,
        weaponTraitLoud,
        weaponTraitPenetrating2,
        weaponTraitTwoHanded,
      ],
    ),
    Weapon(
      id: 12,
      name: 'Lascannon',
      specialisation: WeaponSpecialisation.ordnance,
      damage: '18',
      range: 'Extreme',
      mag: 5,
      enc: 4,
      cost: 8000,
      availability: WeaponAvailability.rare,
      source: 'core book',
      traits: [
        weaponTraitHeavy10,
        weaponTraitLoud,
        weaponTraitPenetrating10,
        weaponTraitTwoHanded,
      ],
    ),
  ],
);

const launcherWeapons = WeaponGroup(
  name: 'Launcher Weapons',
  weapons: [
    Weapon(
      id: 13,
      name: 'Grenade Launcher',
      specialisation: WeaponSpecialisation.ordnance,
      damage: '-',
      range: 'Long',
      mag: 6,
      enc: 2,
      cost: 1000,
      availability: WeaponAvailability.rare,
      source: 'core book',
      traits: [
        weaponTraitLoud,
        weaponTraitTwoHanded,
      ],
    ),
    Weapon(
      id: 14,
      name: 'Portable Missile Launcher',
      specialisation: WeaponSpecialisation.ordnance,
      damage: '-',
      range: 'Extreme',
      mag: 1,
      enc: 3,
      cost: 2000,
      availability: WeaponAvailability.rare,
      source: 'core book',
      traits: [
        weaponTraitHeavy4,
        weaponTraitLoud,
        weaponTraitTwoHanded,
      ],
    ),
  ],
);

const meltaWeapons = WeaponGroup(
  name: 'Melta Weapons',
  weapons: [
    Weapon(
      id: 15,
      name: 'Inferno Pistol',
      specialisation: WeaponSpecialisation.pistol,
      damage: '16',
      range: 'Short',
      mag: 3,
      enc: 0,
      cost: 8000,
      availability: WeaponAvailability.exotic,
      source: 'core book',
      traits: [
        weaponTraitClose,
        weaponTraitRend5,
      ],
    ),
    Weapon(
      id: 16,
      name: 'Meltagun',
      specialisation: WeaponSpecialisation.longGun,
      damage: '16',
      range: 'Medium',
      mag: 5,
      enc: 1,
      cost: 9000,
      availability: WeaponAvailability.rare,
      source: 'core book',
      traits: [
        weaponTraitRend5,
        weaponTraitTwoHanded,
      ],
    ),
  ],
);

const plasmaWeapons = WeaponGroup(
  name: 'Plasma Weapons',
  weapons: [
    Weapon(
      id: 17,
      name: 'Plasma Pistol',
      specialisation: WeaponSpecialisation.pistol,
      damage: '10',
      range: 'Medium',
      mag: 6,
      enc: 1,
      cost: 7000,
      availability: WeaponAvailability.rare,
      source: 'core book',
      traits: [
        weaponTraitClose,
        weaponTraitLoud,
        weaponTraitPenetrating6,
        weaponTraitSupercharge4,
        weaponTraitUnstable,
      ],
    ),
    Weapon(
      id: 18,
      name: 'Plasma Gun',
      specialisation: WeaponSpecialisation.longGun,
      damage: '10',
      range: 'Long',
      mag: 12,
      enc: 1,
      cost: 8000,
      availability: WeaponAvailability.rare,
      source: 'core book',
      traits: [
        weaponTraitLoud,
        weaponTraitPenetrating6,
        weaponTraitSupercharge4,
        weaponTraitTwoHanded,
        weaponTraitUnstable,
      ],
    ),
  ],
);

const solidProjectileWeapons = WeaponGroup(
  name: 'Solid Projectile Weapons',
  weapons: [
    Weapon(
      id: 19,
      name: 'Autopistol',
      specialisation: WeaponSpecialisation.pistol,
      damage: '5',
      range: 'Medium',
      mag: 3,
      enc: 0,
      cost: 400,
      availability: WeaponAvailability.common,
      source: 'core book',
      traits: [
        weaponTraitClose,
        weaponTraitLoud,
        weaponTraitRapidFire3,
      ],
    ),
    Weapon(
      id: 20,
      name: 'Autogun',
      specialisation: WeaponSpecialisation.longGun,
      damage: '6',
      range: 'Long',
      mag: 5,
      enc: 1,
      cost: 600,
      availability: WeaponAvailability.common,
      source: 'core book',
      traits: [
        weaponTraitLoud,
        weaponTraitRapidFire3,
        weaponTraitTwoHanded,
      ],
    ),
    Weapon(
      id: 21,
      name: 'Hand Cannon',
      specialisation: WeaponSpecialisation.pistol,
      damage: '8',
      range: 'Medium',
      mag: 4,
      enc: 2,
      cost: 570,
      availability: WeaponAvailability.scarce,
      source: 'core book',
      traits: [
        weaponTraitClose,
        weaponTraitHeavy4,
        weaponTraitLoud,
        weaponTraitPenetrating2,
      ],
    ),
    Weapon(
      id: 22,
      name: 'Heavy Stubber',
      specialisation: WeaponSpecialisation.ordnance,
      damage: '8',
      range: 'Extreme',
      mag: 8,
      enc: 3,
      cost: 2000,
      availability: WeaponAvailability.scarce,
      source: 'core book',
      traits: [
        weaponTraitHeavy4,
        weaponTraitLoud,
        weaponTraitPenetrating3,
        weaponTraitTwoHanded,
        weaponTraitRapidFire4,
      ],
    ),
    Weapon(
      id: 23,
      name: 'Shotgun (Combat)',
      specialisation: WeaponSpecialisation.longGun,
      damage: '6',
      range: 'Medium',
      mag: 12,
      enc: 1,
      cost: 600,
      availability: WeaponAvailability.scarce,
      source: 'core book',
      traits: [
        weaponTraitInflictProne,
        weaponTraitLoud,
        weaponTraitSpread,
        weaponTraitTwoHanded,
      ],
    ),
    Weapon(
      id: 24,
      name: 'Shotgun (Pump Action)',
      specialisation: WeaponSpecialisation.longGun,
      damage: '6',
      range: 'Medium',
      mag: 8,
      enc: 1,
      cost: 400,
      availability: WeaponAvailability.common,
      source: 'core book',
      traits: [
        weaponTraitInflictProne,
        weaponTraitLoud,
        weaponTraitSpread,
        weaponTraitTwoHanded,
      ],
    ),
    Weapon(
      id: 25,
      name: 'Sniper Rifle',
      specialisation: WeaponSpecialisation.longGun,
      damage: '8',
      range: 'Extreme',
      mag: 6,
      enc: 2,
      cost: 1000,
      availability: WeaponAvailability.scarce,
      source: 'core book',
      traits: [
        weaponTraitLoud,
        weaponTraitTwoHanded,
      ],
    ),
    Weapon(
      id: 26,
      name: 'Stub Pistol',
      specialisation: WeaponSpecialisation.pistol,
      damage: '6',
      range: 'Medium',
      mag: 2,
      enc: 0,
      cost: 250,
      availability: WeaponAvailability.common,
      source: 'core book',
      traits: [
        weaponTraitBurst,
        weaponTraitClose,
        weaponTraitLoud,
      ],
    ),
    Weapon(
      id: 27,
      name: 'Stub Revolver',
      specialisation: WeaponSpecialisation.pistol,
      damage: '6',
      range: 'Medium',
      mag: 6,
      enc: 0,
      cost: 200,
      availability: WeaponAvailability.common,
      source: 'core book',
      traits: [
        weaponTraitClose,
        weaponTraitLoud,
        weaponTraitReliable,
      ],
    ),
  ],
);

const specialisedRangedWeapons = WeaponGroup(
  name: 'Specialised Ranged Weapons',
  weapons: [
    Weapon(
      id: 28,
      name: 'Needle Pistol',
      specialisation: WeaponSpecialisation.pistol,
      damage: '1',
      range: 'Medium',
      mag: 4,
      enc: 1,
      cost: 1500,
      availability: WeaponAvailability.exotic,
      source: 'core book',
      traits: [
        weaponTraitClose,
        weaponTraitInflictPoisoned,
        weaponTraitPenetrating6,
        weaponTraitSubtle,
      ],
    ),
    Weapon(
      id: 29,
      name: 'Needle Rifle',
      specialisation: WeaponSpecialisation.longGun,
      damage: '1',
      range: 'Long',
      mag: 6,
      enc: 2,
      cost: 1700,
      availability: WeaponAvailability.exotic,
      source: 'core book',
      traits: [
        weaponTraitInflictPoisoned,
        weaponTraitPenetrating6,
        weaponTraitSubtle,
        weaponTraitTwoHanded,
      ],
    ),
    Weapon(
      id: 30,
      name: 'Web Pistol',
      specialisation: WeaponSpecialisation.pistol,
      damage: '-',
      range: 'Short',
      mag: 3,
      enc: 1,
      cost: 1300,
      availability: WeaponAvailability.rare,
      source: 'core book',
      traits: [
        weaponTraitClose,
        weaponTraitInflictRestrained,
      ],
    ),
    Weapon(
      id: 31,
      name: 'Webber',
      specialisation: WeaponSpecialisation.longGun,
      damage: '-',
      range: 'Medium',
      mag: 6,
      enc: 1,
      cost: 1500,
      availability: WeaponAvailability.rare,
      source: 'core book',
      traits: [
        weaponTraitInflictRestrained,
        weaponTraitTwoHanded,
      ],
    ),
  ],
);

const presetRangedWeaponGroups = <WeaponGroup>[
  boltWeapons,
  flameWeapons,
  lasWeapons,
  launcherWeapons,
  meltaWeapons,
  plasmaWeapons,
  solidProjectileWeapons,
  specialisedRangedWeapons,
];

final List<Weapon> presetRangedWeapons = List.unmodifiable(
  presetRangedWeaponGroups.expand((group) => group.weapons),
);
