import 'gear.dart';
import 'weapon_availability.dart';

const gearGroupTools = 'Tools';
const gearGroupClothingAndPersonalGear = 'Clothing and Personal Gear';

const presetGearGroups = [
  gearGroupTools,
  gearGroupClothingAndPersonalGear,
];

const presetGear = <Gear>[
  Gear(
    name: 'Auspex/Scanner',
    enc: 1,
    cost: 1000,
    availability: Availability.scarce,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Auto-Quill',
    enc: 2,
    cost: 150,
    availability: Availability.scarce,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: "Chirurgeon's Kit (5 uses)",
    enc: 1,
    cost: 500,
    availability: Availability.rare,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Chrono',
    enc: 0,
    cost: 20,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Climbing Harness',
    enc: 0,
    cost: 100,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Combi-Tool',
    enc: 0,
    cost: 300,
    availability: Availability.rare,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Comm Leech',
    enc: 1,
    cost: 1000,
    availability: Availability.rare,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Dataslate',
    enc: 0,
    cost: 100,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Diagnostor',
    enc: 1,
    cost: 2000,
    availability: Availability.rare,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Disguise Kit',
    enc: 1,
    cost: 100,
    availability: Availability.veryRare,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: "Emperor's Tarot",
    enc: 0,
    cost: 10000,
    availability: Availability.rare,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Entrenching Tool',
    enc: 1,
    cost: 20,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Excruciator Kit',
    enc: 1,
    cost: 500,
    availability: Availability.exotic,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Glow-Globe/Stablight',
    enc: 0,
    cost: 30,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Grapnel Launcher',
    enc: 0,
    cost: 550,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Grav Chute',
    enc: 2,
    cost: 2000,
    availability: Availability.rare,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Holy Icon',
    enc: 0,
    cost: 10,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Inhaler/Injector',
    enc: 0,
    cost: 65,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Instruments of Divination',
    enc: 0,
    cost: 200,
    availability: Availability.rare,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Lascutter',
    enc: 2,
    cost: 170,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Laud Hailer',
    enc: 1,
    cost: 100,
    availability: Availability.scarce,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Mag Boots',
    enc: 0,
    cost: 400,
    availability: Availability.rare,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Magnoculars',
    enc: 0,
    cost: 30,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Manacles',
    enc: 0,
    cost: 50,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Micro-Bead/Vox Bead',
    enc: 0,
    cost: 150,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Monotask Servo-Skull',
    enc: 0,
    cost: 2000,
    availability: Availability.rare,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Multicompass',
    enc: 0,
    cost: 400,
    availability: Availability.exotic,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Multikey',
    enc: 0,
    cost: 200,
    availability: Availability.scarce,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Pict Recorder',
    enc: 0,
    cost: 200,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Psy Focus',
    enc: 0,
    cost: 100,
    availability: Availability.exotic,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Regicide Set',
    enc: 0,
    cost: 40,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Sacred Unguents (5 uses)',
    enc: 0,
    cost: 100,
    availability: Availability.rare,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Screamer',
    enc: 1,
    cost: 170,
    availability: Availability.scarce,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Signal Jammer',
    enc: 1,
    cost: 250,
    availability: Availability.rare,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Stummer',
    enc: 1,
    cost: 1000,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Vox-Caster',
    enc: 0,
    cost: 1000,
    availability: Availability.scarce,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Writing Kit',
    enc: 1,
    cost: 20,
    availability: Availability.common,
    group: gearGroupTools,
    source: 'core book',
  ),
  Gear(
    name: 'Backpack/Slings',
    enc: 1,
    cost: 20,
    availability: Availability.common,
    group: gearGroupClothingAndPersonalGear,
    source: 'core book',
  ),
  Gear(
    name: 'Cameleoline Cloak',
    enc: 0,
    cost: 500,
    availability: Availability.rare,
    group: gearGroupClothingAndPersonalGear,
    source: 'core book',
  ),
  Gear(
    name: 'Explosive Collar',
    enc: 0,
    cost: 150,
    availability: Availability.scarce,
    group: gearGroupClothingAndPersonalGear,
    source: 'core book',
  ),
  Gear(
    name: 'Filtration Plugs',
    enc: 0,
    cost: 20,
    availability: Availability.common,
    group: gearGroupClothingAndPersonalGear,
    source: 'core book',
  ),
  Gear(
    name: 'Photo-Visors/Contacts',
    enc: 0,
    cost: 300,
    availability: Availability.scarce,
    group: gearGroupClothingAndPersonalGear,
    source: 'core book',
  ),
  Gear(
    name: 'Rebreather',
    enc: 1,
    cost: 200,
    availability: Availability.scarce,
    group: gearGroupClothingAndPersonalGear,
    source: 'core book',
  ),
  Gear(
    name: 'Respirator/Gas Mask',
    enc: 0,
    cost: 50,
    availability: Availability.common,
    group: gearGroupClothingAndPersonalGear,
    source: 'core book',
  ),
  Gear(
    name: 'Survival Gear',
    enc: 3,
    cost: 50,
    availability: Availability.common,
    group: gearGroupClothingAndPersonalGear,
    source: 'core book',
  ),
  Gear(
    name: 'Synskin',
    enc: 0,
    cost: 3000,
    availability: Availability.exotic,
    group: gearGroupClothingAndPersonalGear,
    source: 'core book',
  ),
  Gear(
    name: 'Void Suit',
    enc: 2,
    cost: 2000,
    availability: Availability.scarce,
    group: gearGroupClothingAndPersonalGear,
    source: 'core book',
  ),
];
