import 'preset_weapon_traits.dart';
import 'weapon.dart';
import 'weapon_availability.dart';
import 'weapon_group.dart';
import 'weapon_specialisation.dart';

const grenadesAndExplosives = WeaponGroup(
  name: 'Grenades and Explosives',
  weapons: [
    Weapon(
      id: 32,
      name: 'Blasting Charge',
      specialisation: WeaponSpecialisation.thrown,
      damage: '10',
      enc: 0,
      cost: 40,
      availability: Availability.common,
      source: 'core book',
      traits: [
        weaponTraitLoud,
        weaponTraitSpread,
        weaponTraitThrownMedium,
        weaponTraitUnstable,
      ],
    ),
    Weapon(
      id: 33,
      name: 'Choke Grenade',
      specialisation: WeaponSpecialisation.thrownOrdnance,
      damage: '-',
      enc: 0,
      cost: 40,
      availability: Availability.scarce,
      source: 'core book',
      traits: [
        weaponTraitInflictStunned,
        weaponTraitThrownMedium,
        weaponTraitUnstable,
      ],
    ),
    Weapon(
      id: 34,
      name: 'Demolition Charge',
      specialisation: WeaponSpecialisation.engineering,
      damage: '16',
      enc: 2,
      cost: 50,
      availability: Availability.common,
      source: 'core book',
      traits: [
        weaponTraitLoud,
        weaponTraitSpread,
        weaponTraitUnstable,
      ],
    ),
    Weapon(
      id: 35,
      name: 'Fire Bomb',
      specialisation: WeaponSpecialisation.thrown,
      damage: '-',
      enc: 1,
      cost: 10,
      availability: Availability.common,
      source: 'core book',
      traits: [
        weaponTraitBlast,
        weaponTraitLoud,
        weaponTraitInflictAblaze,
        weaponTraitThrownMedium,
        weaponTraitUnstable,
      ],
    ),
    Weapon(
      id: 36,
      name: 'Frag Grenade',
      specialisation: WeaponSpecialisation.thrownOrdnance,
      damage: '6',
      enc: 0,
      cost: 50,
      availability: Availability.common,
      source: 'core book',
      traits: [
        weaponTraitBlast,
        weaponTraitLoud,
        weaponTraitThrownMedium,
        weaponTraitUnstable,
      ],
    ),
    Weapon(
      id: 37,
      name: 'Frag Missile',
      specialisation: WeaponSpecialisation.ordnance,
      damage: '8',
      enc: 1,
      cost: 200,
      availability: Availability.scarce,
      source: 'core book',
      traits: [
        weaponTraitBlast,
        weaponTraitLoud,
        weaponTraitUnstable,
      ],
    ),
    Weapon(
      id: 38,
      name: 'Krak Grenade',
      specialisation: WeaponSpecialisation.thrownOrdnance,
      damage: '12',
      enc: 0,
      cost: 60,
      availability: Availability.rare,
      source: 'core book',
      traits: [
        weaponTraitLoud,
        weaponTraitPenetrating4,
        weaponTraitSpread,
        weaponTraitThrownMedium,
        weaponTraitUnstable,
      ],
    ),
    Weapon(
      id: 39,
      name: 'Krak Missile',
      specialisation: WeaponSpecialisation.ordnance,
      damage: '16',
      enc: 1,
      cost: 400,
      availability: Availability.scarce,
      source: 'core book',
      traits: [
        weaponTraitLoud,
        weaponTraitPenetrating6,
        weaponTraitSpread,
        weaponTraitUnstable,
      ],
    ),
    Weapon(
      id: 40,
      name: 'Melta Bomb',
      specialisation: WeaponSpecialisation.engineering,
      damage: '16',
      enc: 2,
      cost: 1000,
      availability: Availability.exotic,
      source: 'core book',
      traits: [
        weaponTraitRend12,
        weaponTraitSpread,
        weaponTraitUnstable,
      ],
    ),
    Weapon(
      id: 41,
      name: 'Photon Flash Grenade',
      specialisation: WeaponSpecialisation.thrownOrdnance,
      damage: '-',
      enc: 0,
      cost: 200,
      availability: Availability.rare,
      source: 'core book',
      traits: [
        weaponTraitLoud,
        weaponTraitInflictBlinded,
        weaponTraitThrownMedium,
        weaponTraitUnstable,
      ],
    ),
    Weapon(
      id: 42,
      name: 'Smoke Grenade',
      specialisation: WeaponSpecialisation.thrownOrdnance,
      damage: '-',
      enc: 0,
      cost: 30,
      availability: Availability.common,
      source: 'core book',
      traits: [
        weaponTraitBlast,
        weaponTraitThrownMedium,
        weaponTraitUnstable,
      ],
    ),
    Weapon(
      id: 43,
      name: 'Web Grenade',
      specialisation: WeaponSpecialisation.thrown,
      damage: '-',
      enc: 0,
      cost: 150,
      availability: Availability.rare,
      source: 'core book',
      traits: [
        weaponTraitLoud,
        weaponTraitBlast,
        weaponTraitInflictRestrained,
        weaponTraitThrownMedium,
        weaponTraitUnstable,
      ],
    ),
  ],
);

const presetGrenadeAndExplosiveGroups = <WeaponGroup>[
  grenadesAndExplosives,
];

final List<Weapon> presetGrenadesAndExplosives = List.unmodifiable(
  presetGrenadeAndExplosiveGroups.expand((group) => group.weapons),
);
